dataset_path: data
seed: 42
data_loader:
  train:
    batch_size: 1
    # batch_size: 4
    num_workers: 8
    shuffle: true
  test:
    batch_size: 1
    shuffle: false
train:
  initial_learning_rate: 1e-4
  # initial_learning_rate: 1e-3
  # weight_decay: 0.0001
  pct_start: 0.05
  epochs: 100


model:
  name: idnet
  # update_iters: 4 # idnet
  # hidden_dim: 96 # idnet
  # downsample: 8 # idnet
  # pretrain_ckpt: idn/id-8x.pt
  update_iters: 4 # idnet
  hidden_dim: 128 # idnet
  downsample: 4 # idnet
  pretrain_ckpt: idn/id-4x.pt
  # name: evflownet
  # no_batch_norm: false # EVFlowNet
  # input_channel: ${dataset.num_voxel_bins} # EVFlowNet

loss:
  name: l2+smooth
  lambda: 0.5

dataset:
  num_voxel_bins: 10
  train:
    downsample_ratio: 1
    horizontal_flip: 0.5
    # random_rotate: 10

    exclude_seqs:
      - seq_1
