dataset_path: data
seed: 42
data_loader:
  common:
    num_voxel_bins: 15
  train:
    batch_size: 4
    num_workers: 6
    shuffle: true
  test:
    batch_size: 1
    shuffle: false
train:
  initial_learning_rate: 5e-4 # 0.01
  weight_decay: 0.0001
  epochs: 10

model:
  name: IDEDEQIDO
  update_iters: 4
  hidden_dim: 96
  downsample: 8
  pretrain_ckpt: idn/id-8x.pt
  # hidden_dim: 128
  # downsample: 4
  # pretrain_ckpt: idn/id-4x.pt
  # no_batch_norm: false # EVFlowNet

dataset:
  train:
    downsample_ratio: 1
    horizontal_flip: 0.5
    # vertical_flip: 0.1
    # random_crop: [288, 384]

